on: [push]

jobs:
  report_job:
    runs-on: ubuntu-latest
    name: A job to report to slack
    steps:
      - uses: actions/checkout@v4
      - name: Report to slack
        uses: kenfdev/playwright-report-slack-action@v1
        with:
          results-json-path: 'report.json'
          artifact-url: 'https://test.test'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
